### ISSUE TITLE
Could you please explain how to compile in README ?

### ISSUE THREAD

**Issue by stmoon** [DrTon/FlightPlot#38]
I'm newbie of development of flightplot.
I think flightplot is very useful application for pixhawk. 
In order to develop with other developer, I think the readme should be more detailed.
Especially, how to compile, how to insert module, and so on....

I just install intelliJ. However, I cannot compile with many problem. 
please explain how to compile it...

**Comment by stmoon** [comment]
I just run "ant"... however please comment how to compile 
anyway thanks

**Comment by DrTon** [comment]
Feel free to edit README by adding answers for your questions, if you found it and send PR. That would be useful contribution. Probably somebody will have the same questions. I will correct it if needed.

**Comment by stmoon** [comment]
Thank you 

I will modify readme if you want


2015. 9. 13. 오전 5:44 Anton Babushkin <notifications@github.com> 작성:
