### ISSUE TITLE
add vehicle orientation and waypoints to KML track

### ISSUE THREAD

**Issue by kd0aij** [DrTon/FlightPlot#46]
example KMZ file from the MatrixPilot team: https://copy.com/EwpjLqTocNjcEopK

Google Earth snapshot of landing: 
![finish_manual_landing](https://cloud.githubusercontent.com/assets/2300221/8699670/6c4a438a-2ac4-11e5-9bfa-d04bb98ee981.jpg)

snapshot showing magnetic north on autonomous takeoff: 
![log2260_mag](https://cloud.githubusercontent.com/assets/2300221/8699690/860a15ac-2ac4-11e5-8ea3-5ece5eebfa78.jpg)

snapshot showing orientation through turn-around at WP2:
![wp2_180](https://cloud.githubusercontent.com/assets/2300221/8699792/49b3dd94-2ac5-11e5-8396-abf7ab31a60f.jpg)

**Comment by DrTon** [comment]
Thanks! Looks good and a lot of useful features!

**Comment by kd0aij** [comment]
development has moved to the PX4 fork
