### ISSUE TITLE
GPS.Altitude View Problem

### ISSUE THREAD

**Issue by tubeme** [DrTon/FlightPlot#59]
Hi first thanks for the great app. I have this rather inconvenient problem with the view. Here our home spot is at 600-650 meters altitude we fly at 600-900 meters height so When I turn on the GPS.Alt in the view the number is so high that all the other graphics get almost like a line around the 0 point. It is especially inconvenient when we have to analyze VTOL transitions. So please can you add a way that FlightPlot detects where the 0 ground is and provide in some way Relative Altitude Visualization instead of the GPS.Alt in real numbers.

![gpsalt](https://cloud.githubusercontent.com/assets/12617619/13336765/8ab91bd0-dc20-11e5-8455-bfbff25c2fc1.png)

**Comment by AndreasAntener** [comment]
@tubeme for every field you add you can set an offset to correct that. So in your case you would set an offset of for example -550 to the GPS.Alt field.

A convenience feature to make this automatic by specifying ground height would be cool. Could be done for fields we know they contain an absolute altitude. In the meantime, please use the offset.

**Comment by AndreasAntener** [comment]
Closing this, opened a feature issue: https://github.com/DrTon/FlightPlot/issues/60
