### ISSUE TITLE
FlightPlot Fork

### ISSUE THREAD

**Issue by bkueng** [DrTon/FlightPlot#68]
Hi @DrTon 

First, many thanks for creating and maintaining this project! It's been very useful to us (PX4 team), and we would like to continue using it. However in several weeks you have not answered to any pull request, and we would like to continue the development (in particular adding/extending support for the ULog file format). So this is not an easy step, but should we not hear back from you, we will keep our own fork at https://github.com/PX4/FlightPlot and release versions for it.

Should you decide to take up development again, you can of course take over and be the primary maintainer. We can also do a shared maintainership if you have too many other things to do, or some other model, but the current state hinders development.

FYI @kd0aij @dagar @AndreasAntener @LorenzMeier

**Comment by DrTon** [comment]
Hi! Sorry, that was just notification problem, now tuned notifications and should be more responsive :) Anyway please feel free to contact me via email/skype in case of silence.

**Comment by bkueng** [comment]
That's great! Can you look at the open PR's then?
