### ISSUE TITLE
How to turn OFF Low-pass filter in Expression?

### ISSUE THREAD

**Issue by copterspace** [DrTon/FlightPlot#78]
I tune my Optical Flow sensor, and with help of Expression fields I'd like to bring several fields to single scale (for example: optical_flow_0.pixel_flow_y_integral * 100, or optical_flow_0.quality / 100)

But I found out, when I use Expression field - not only expression is calculated, but also LPF is applied somehow, which changes the appearence of the field graphic completely.

For example: this if graphics for optical_flow_0.pixel_flow_y_integral - red - Simple, Blue - Expression.
LPF = 0, should be no filtering, but graphics completely different.

![изображение](https://user-images.githubusercontent.com/38784273/73818368-a268c400-4806-11ea-8041-ce8f0eb7a188.png)

How to turn off the low pass filtering in the Expression field?

**Comment by DrTon** [comment]
It's not LPF issue, but just delay, you can notice that if you add steps to red line and shift it by one sample you will get blue line. 'Expression' is experimantal processor for complex expressions, and it adds new point on every update of any stream, for this reason you see much more points. For scaling is better to use 'Scale' and 'Offset' parameters of 'Simple' processor.

**Comment by copterspace** [comment]
Антон, спасибо огромное, Simple + Scale - то что надо, очень помогло.
Anton, thank you so much, Simple + Scale helped a lot.
